openapi: 3.0.3
info:
  title: WalletConnect Pay API (Gateway)
  description: Gateway API for wallets to fulfill WalletConnect Pay payments (API-first / non-SDK flow).
  version: 0.0.0
servers:
  - url: https://api.pay.walletconnect.com
paths:
  /v1/gateway/payment/{id}/options:
    post:
      tags:
        - Gateway
      summary: Get payment options
      description: This endpoint takes a list of accounts and returns a list of options that can be used to complete the payment.
      operationId: gatewayGetPaymentOptions
      parameters:
        - name: Api-Key
          in: header
          required: true
          schema:
            type: string
        - name: App-Id
          in: header
          required: false
          schema:
            type: string
        - name: id
          in: path
          description: Payment ID
          required: true
          schema:
            type: string
        - name: includePaymentInfo
          in: query
          description: Whether to include payment information in the response
          required: false
          schema:
            type: boolean
            nullable: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetPaymentOptionsRequest"
      responses:
        "200":
          description: Payment options retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPaymentOptionsResponse"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Invalid API key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /v1/gateway/payment/{id}/fetch:
    post:
      tags:
        - Gateway
      summary: Fetch an action
      description: This endpoint fetches an action for a payment.
      operationId: fetch_handler
      parameters:
        - name: Api-Key
          in: header
          required: true
          schema:
            type: string
        - name: App-Id
          in: header
          required: false
          schema:
            type: string
        - name: id
          in: path
          description: Payment ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FetchRequest"
            example:
              data: "..."
              optionId: opt_123
      responses:
        "200":
          description: Action built successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FetchResponse"
              example:
                actions:
                  - data:
                      chain_id: eip155:8453
                      method: eth_signTypedData_v4
                      params:
                        - "0x0000000000000000000000000000000000000000"
                        - "{\"domain\":{\"name\":\"USD Coin\",\"version\":\"2\",\"chainId\":\"0x2105\",\"verifyingContract\":\"0x0000000000000000000000000000000000000000\"},\"types\":{\"EIP712Domain\":[{\"type\":\"string\",\"name\":\"name\"},{\"type\":\"string\",\"name\":\"version\"},{\"type\":\"uint256\",\"name\":\"chainId\"},{\"type\":\"address\",\"name\":\"verifyingContract\"}],\"TransferWithAuthorization\":[{\"type\":\"address\",\"name\":\"from\"},{\"type\":\"address\",\"name\":\"to\"},{\"type\":\"uint256\",\"name\":\"value\"},{\"type\":\"uint256\",\"name\":\"validAfter\"},{\"type\":\"uint256\",\"name\":\"validBefore\"},{\"type\":\"bytes32\",\"name\":\"nonce\"}]},\"primaryType\":\"TransferWithAuthorization\",\"message\":{\"from\":\"0x0000000000000000000000000000000000000000\",\"nonce\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"to\":\"0x0000000000000000000000000000000000000000\",\"validAfter\":\"0x0\",\"validBefore\":\"0x0\",\"value\":\"0x0\"}}"
                    type: walletRpc
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Invalid API key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /v1/gateway/payment/{id}/confirm:
    post:
      tags:
        - Gateway
      summary: Confirm a payment
      description: "This endpoint confirms a payment and submits it to the blockchain for processing."
      operationId: confirm_payment_handler
      parameters:
        - name: Api-Key
          in: header
          required: true
          schema:
            type: string
        - name: App-Id
          in: header
          required: false
          schema:
            type: string
        - name: id
          in: path
          description: Payment ID
          required: true
          schema:
            $ref: "#/components/schemas/PaymentId"
        - name: maxPollMs
          in: query
          description: Maximum time to long-poll for payment status, in milliseconds.
          required: false
          schema:
            type: integer
            nullable: true
            format: int64
            minimum: 0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConfirmPaymentRequest"
            example:
              collectedData:
                fields:
                  - id: fullName
                    value: John Smith
                  - id: dob
                    value: "1990-01-01"
                  - id: tosConfirmed
                    value: "true"
              optionId: opt_123
              results:
                - data:
                    - "0x123"
                  type: walletRpc
      responses:
        "200":
          description: Payment confirmed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmPaymentResponse"
              example:
                isFinal: true
                pollInMs: null
                status: succeeded
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Invalid API key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    Action:
      oneOf:
        - type: object
          description: An action that requires a wallet RPC call to complete
          required:
            - data
            - type
          properties:
            data:
              $ref: "#/components/schemas/WalletRpcAction"
              description: An action that requires a wallet RPC call to complete
            type:
              type: string
              enum:
                - walletRpc
        - type: object
          description: An action that requires building to complete
          required:
            - data
            - type
          properties:
            data:
              $ref: "#/components/schemas/Build"
              description: An action that requires building to complete
            type:
              type: string
              enum:
                - build
    Amount:
      type: object
      required:
        - unit
        - value
        - display
      properties:
        display:
          $ref: "#/components/schemas/AmountDisplay"
          description: Display information for the amount
        unit:
          type: string
          description: Currency unit, prefixed with either "iso4217/" or "caip19/"
        value:
          type: string
          description: Amount value, in the currency unit's minor units
    AmountDisplay:
      type: object
      required:
        - assetSymbol
        - assetName
        - decimals
      properties:
        assetName:
          type: string
          description: Full name of the asset
        assetSymbol:
          type: string
          description: Ticker/symbol of the asset
        decimals:
          type: integer
          format: int32
          description: Number of minor decimals of the asset
          minimum: 0
        iconUrl:
          type: string
          nullable: true
          description: URL of the icon of the asset (if token)
        networkIconUrl:
          type: string
          nullable: true
          description: URL of the icon of the network
        networkName:
          type: string
          nullable: true
          description: Name of the network of the asset (if token)
    Build:
      type: object
      required:
        - data
      properties:
        data:
          type: string
    BuyerInfo:
      type: object
      required:
        - accountCaip10
        - accountProviderName
      properties:
        accountCaip10:
          type: string
          description: Account CAIP-10
        accountProviderIcon:
          type: string
          nullable: true
          description: Account provider icon URL
        accountProviderName:
          type: string
          description: Account provider name
    CollectData:
      type: object
      properties:
        url:
          type: string
          description: WebView URL for data collection
        schema:
          type: object
          nullable: true
          description: JSON schema describing the required fields
        fields:
          type: array
          items:
            $ref: "#/components/schemas/CollectDataField"
    CollectDataField:
      type: object
      required:
        - type
        - id
        - name
        - required
      properties:
        id:
          type: string
          description: ID of the field for submission
        name:
          type: string
          description: Human readable name of the field
        required:
          type: boolean
          description: Requiredness of the field
        type:
          $ref: "#/components/schemas/CollectDataFieldType"
          description: Type of the field
    CollectDataFieldResult:
      type: object
      required:
        - id
        - value
      properties:
        id:
          type: string
        value:
          type: string
    CollectDataFieldType:
      type: string
      enum:
        - text
        - date
    CollectDataResult:
      type: object
      required:
        - fields
      properties:
        fields:
          type: array
          items:
            $ref: "#/components/schemas/CollectDataFieldResult"
    ConfirmPaymentRequest:
      type: object
      required:
        - optionId
        - results
      properties:
        collectedData:
          allOf:
            - $ref: "#/components/schemas/CollectDataResult"
          nullable: true
        optionId:
          type: string
          description: ID of the option to confirm
        results:
          type: array
          items:
            $ref: "#/components/schemas/ConfirmPaymentResult"
    ConfirmPaymentResponse:
      type: object
      required:
        - status
        - isFinal
      properties:
        isFinal:
          type: boolean
          description: True if the payment is in a final state and no longer requires polling
        pollInMs:
          type: integer
          nullable: true
          format: int64
          description: Time to poll for payment status, in milliseconds. Not present if the payment is in a final state.
          minimum: 0
        status:
          $ref: "#/components/schemas/PaymentStatus"
          description: Payment status
    ConfirmPaymentResult:
      oneOf:
        - type: object
          required:
            - data
            - type
          properties:
            data:
              type: array
              items: {}
            type:
              type: string
              enum:
                - walletRpc
    ErrorCode:
      type: string
      description: Standard error codes for API responses.
      enum:
        - rate_limited
        - invalid_params
        - params_validation
        - payment_not_found
        - internal_error
        - invalid_api_key
        - unauthorized
        - forbidden
        - invalid_state
        - missing_api_key
        - missing_merchant_api_key
        - missing_merchant_id
        - header_not_ascii
        - not_sandbox_api_key
        - merchant_not_found
        - merchant_exists
        - api_key_not_found
    ErrorResponse:
      type: object
      description: Standard error response structure for API errors.
      required:
        - code
        - message
      properties:
        code:
          $ref: "#/components/schemas/ErrorCode"
        message:
          type: string
    FetchRequest:
      type: object
      required:
        - optionId
        - data
      properties:
        data:
          type: string
          description: Extra data to be passed
        optionId:
          type: string
          description: ID of the option to build an action for
    FetchResponse:
      type: object
      required:
        - actions
      properties:
        actions:
          type: array
          items:
            $ref: "#/components/schemas/Action"
    GetPaymentOptionsRequest:
      type: object
      required:
        - accounts
      properties:
        accounts:
          type: array
          items:
            type: string
        refresh:
          type: array
          nullable: true
          items:
            type: string
    GetPaymentOptionsResponse:
      type: object
      required:
        - options
      properties:
        collectData:
          allOf:
            - $ref: "#/components/schemas/CollectData"
          nullable: true
        info:
          allOf:
            - $ref: "#/components/schemas/GetPaymentResponse"
          nullable: true
        options:
          type: array
          items:
            $ref: "#/components/schemas/PaymentOption"
    GetPaymentResponse:
      type: object
      required:
        - status
        - amount
        - expiresAt
        - merchant
      properties:
        amount:
          $ref: "#/components/schemas/Amount"
          description: Amount to be paid
        buyer:
          allOf:
            - $ref: "#/components/schemas/BuyerInfo"
          nullable: true
        expiresAt:
          type: integer
          format: int64
          description: Payment expiration timestamp, in seconds since epoch
          minimum: 0
        merchant:
          $ref: "#/components/schemas/MerchantInfo"
          description: Merchant information
        status:
          $ref: "#/components/schemas/PaymentStatus"
          description: Payment status
    MerchantInfo:
      type: object
      required:
        - name
      properties:
        iconUrl:
          type: string
          nullable: true
          description: Merchant icon URL
        name:
          type: string
          description: Merchant name
    PaymentId:
      type: string
      description: Payment ID
    PaymentOption:
      type: object
      required:
        - id
        - amount
        - etaS
        - actions
      properties:
        account:
          type: string
          description: CAIP-10 account identifier for this option
        actions:
          type: array
          items:
            $ref: "#/components/schemas/Action"
          description: Actions required to complete the option
        amount:
          $ref: "#/components/schemas/Amount"
          description: The option's token and amount
        etaS:
          type: integer
          format: int64
          description: Estimated time to complete the option, in seconds
          minimum: 0
        collectData:
          allOf:
            - $ref: "#/components/schemas/CollectData"
          nullable: true
          description: Per-option data collection requirements. When present, the user must complete data collection before confirming this option.
        id:
          type: string
          description: ID of the option to be used to refer to it in other requests. May be up to 2^16 characters.
    PaymentStatus:
      type: string
      description: Payment status representing the lifecycle of a payment.
      enum:
        - requires_action
        - processing
        - succeeded
        - failed
        - expired
    WalletRpcAction:
      type: object
      required:
        - chain_id
        - method
        - params
      properties:
        chain_id:
          type: string
        method:
          type: string
        params:
          type: array
          items: {}
  securitySchemes:
    API Key:
      type: apiKey
      in: header
      name: Api-Key
security:
  - API Key: []
